# Generated by Django 5.2.6 on 2025-09-17 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(default=2, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='salery',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
